apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    group: backend
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-secret-volume
            mountPath: "/usr/share/nginx/html/index.html"
            readOnly: true
            subPath: "index.html"
      volumes:
      - name: nginx-secret-volume
        projected:
          sources:
          - secret:
              name: nginx-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  index.html: PHBhdGg6c2VjcmV0L2RhdGEvbmdpbnhzZWNyZXQjbWVzc2FnZT4K
